### ISSUE TITLE
XHTML + RDFa ? 

### ISSUE THREAD

**Issue by ekansa** [pelagios/pelagios-widgets#105]
I'm working on adding the place widget to Open Context (see example: http://opencontext.org/subjects/766ED8AA-3147-4CA2-6ECA-BD96BE0433BE ). Do we have an example that works for XHTML+RDFa (and still validates)?

Thanks!
-Eric

**Comment by julietteculver** [comment]
[This appeared as a comment in a different issue in the notification email for some reason, so I added a separate issue for this before I realised you logged a new issue]

There is a separate issue for this here: #122
